// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------------ //
// bu79100g_parallel3 //
// ------------------ //

#define bu79100g_parallel3_wrap_target 0
#define bu79100g_parallel3_wrap 12
#define bu79100g_parallel3_pio_version 1

static const uint16_t bu79100g_parallel3_program_instructions[] = {
            //     .wrap_target
    0xf801, //  0: set    pins, 1         side 1
    0x208b, //  1: wait   1 gpio, 11
    0x200b, //  2: wait   0 gpio, 11
    0xf800, //  3: set    pins, 0         side 1
    0xf82f, //  4: set    x, 15           side 1
    0xb042, //  5: nop                    side 0
    0x1845, //  6: jmp    x--, 5          side 1
    0xf801, //  7: set    pins, 1         side 1
    0xf82f, //  8: set    x, 15           side 1
    0xe000, //  9: set    pins, 0
    0x5004, // 10: in     pins, 4         side 0
    0x184a, // 11: jmp    x--, 10         side 1
    0xf801, // 12: set    pins, 1         side 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program bu79100g_parallel3_program = {
    .instructions = bu79100g_parallel3_program_instructions,
    .length = 13,
    .origin = -1,
    .pio_version = bu79100g_parallel3_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x1
#endif
};

static inline pio_sm_config bu79100g_parallel3_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + bu79100g_parallel3_wrap_target, offset + bu79100g_parallel3_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

